server :
    port : 10007
spring :
    application :
        name : joomall-search

    thymeleaf:
        cache: false

    cloud :
        nacos :
            discovery :
                server-addr : 127.0.0.1:8848

