server :
    port : 10004
spring :
    application :
        name : joomall-member
    datasource :
        driver-class-name : com.mysql.cj.jdbc.Driver
        username : root
        password : 88888888
        url : jdbc:mysql://127.0.0.1:3306/joomall_member?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    cloud :
        nacos :
            discovery :
                namespace : public
                server-addr : 127.0.0.1:8848
# MapperScan sql.xml映射文件位置
mybatis-plus :
    mapper-locations : classpath:/mapper/**/*.xml
    global-config :
        db-config :
            id-type : auto