server:
  port: 10006
spring:
  application:
    name: joomall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t67ect4d7se82xEeCR5
      secret-key: Q9ht0ulNQ9zx8lBQcuDn91zhzE26h1
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: joomall

